### PR TITLE
Compile v4 on linux (dirty patch)

### PR DESCRIPTION
**Pull request by dguerizec**
Hi,

This is a dirty patch to make the version4 compile and run on linux. It is not meant to be merged, but is just a hint on what didn't pass the compilation.

(I had the opportunity to play a bit with it, it looks promising !)

### CODE REVIEW

**Comment by chrxh** [comment]
Thanks a lot! I'll keep your PR open.

It's a pity that ImFileDialog is no longer maintained :-( I already had to make a dirty patch to fix compile errors due to std::u8string issues when activating C++20.

**Comment by chrxh** [comment]
I have been working a lot on `version4` and plan to merge it to `develop` soon. If you are still willing to help, would you please check the gcc compile errors? There is an Ubunti-Ci configured on `develop` to ensure that it will remain compilable.

**Comment by caichenyi92** [comment]
您好，您的邮件已收到，我会尽快回复，谢谢。

    


    


    蔡陈翼


    东南大学建筑学院
南京市玄武区四牌楼2号Tel：18652966253

**Comment by chrxh** [comment]
I have fixed the gcc compile errors in the meantime. If there are still problems, feel free to create a new PR.

**Pull request closed without merging**
