### PR TITLE
Added # comments in code, and symbols decompilation in comments.

### PR DESCRIPTION
**Pull request by dguerizec**
Hello,

I made this PR because I was frustrated with non-human readable code in replicated cells.
What it does, is trying to replace numbers with symbols where applicable, and write what could be a version of the original code in end-of-line # comments.
These comments have to pass the compilation process, so the code stays editable without burdens.
Due to the nature of the symbols map, it can't be perfect, but it's working pretty well most of the time.

### CODE REVIEW

**Comment by caichenyi92** [comment]
您好，您的邮件已收到，我会尽快回复，谢谢。

    


    


    蔡陈翼


    东南大学建筑学院
南京市玄武区四牌楼2号Tel：18652966253

**Comment by chrxh** [comment]
Hi,

this seems to be a useful extension! I'll have a closer look at it tomorrow.

In the upcoming version, however, the machine code will be replaced by neural networks (and the entire simulation model modified) because they are more amenable to evolutionary adaptation and learning methods. The development can be found on the branch https://github.com/chrxh/alien/tree/version4 and is not finished yet. You can find more extensions (e.g. genetic editor) and some code refactorings there.

I'll keep the current version, which allows cells to operate on the basis of machine code, on an extra branch in the future.

**Comment by dguerizec** [comment]
I've checked the version4, but failed to compile it on linux. Maybe I'll give it another try later, when I have time to fix compilation quirks.
I love the idea of neural networks! I was a bit disappointed when I saw a NN cell type... but disabled.
I wonder if the simulation will evolve as fast in the v4 as it does in the v3, if there is no code to bootstrap some "fixed" behaviors.
I personally see the code as DNA genes (genome), and the NN as the brain connections (connectome). Both can be subject to mutations, but one is static and the other is plastic (over the lifetime of an organism).
I could elaborate on this subject, but this is not the place :)
Anyway, I'm looking forward to check the version 4!

**Comment by chrxh** [comment]
I've tested your feature. It works well and I find it very useful. I'll merge the PR.
The Ubuntu CI is complaining but it seems nothing to do with your changes. It has not been running for over a month. There were probably changes in the toolchain.
I'll have a look at it when I find time. If you have any idea of the reason, I'd be happy to know :)
Anyway, thanks a lot for your contribution!

I'm doing the development to version 4.0 on my Windows PC, so it's quite likely that it doesn't compile on other platforms yet. I will fix that at a later time.

**Comment by chrxh** [comment]
Sorry, I forgot to answer your question:

> I wonder if the simulation will evolve as fast in the v4 as it does in the v3, if there is no code to bootstrap some "fixed" behaviors.

Most of the "fixed behavior" or configurations will be set directly as properties in the cell functions. Most important, however, is that the constructor cells contains a genome. It encodes an entire cell cluster with configurations for all its cells. There will be a new editor for genomes.
I attach a screenshot:

Genome editor

**Pull request merged**
